package com.example.util

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.os.Environment
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.data.model.CalculationRecord
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object ReportExporter {

  fun formatTextReport(record: CalculationRecord): String {
    val dateStr = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault()).format(Date(record.timestampMillis))
    val sb = StringBuilder()
    sb.appendLine("════════════════════════════════════════════")
    sb.appendLine("            F A I Z A N  R A Z A            ")
    sb.appendLine("   CA CALCULATOR — CHARTERED ACCOUNTANT TOOL ")
    sb.appendLine("════════════════════════════════════════════")
    sb.appendLine("Module    : ${record.moduleTitle}")
    sb.appendLine("Calculator: ${record.calculatorTitle}")
    sb.appendLine("Date      : $dateStr")
    sb.appendLine("────────────────────────────────────────────")
    sb.appendLine("INPUT PARAMETERS:")
    sb.appendLine(record.inputSummary)
    sb.appendLine("────────────────────────────────────────────")
    sb.appendLine("RESULT BREAKDOWN:")
    for (row in record.detailedRows) {
      sb.appendLine(" • ${row.label}: ${row.value}")
      if (row.footnote.isNotEmpty()) {
        sb.appendLine("   (${row.footnote})")
      }
    }
    sb.appendLine("════════════════════════════════════════════")
    sb.appendLine("Generated by CA Calculator — India's Premier Commerce Tool")
    return sb.toString()
  }

  fun shareTextReport(context: Context, record: CalculationRecord) {
    val reportText = formatTextReport(record)
    val sendIntent = Intent().apply {
      action = Intent.ACTION_SEND
      putExtra(Intent.EXTRA_TITLE, "CA Calculator Report: ${record.calculatorTitle}")
      putExtra(Intent.EXTRA_TEXT, reportText)
      type = "text/plain"
    }
    val shareIntent = Intent.createChooser(sendIntent, "Share CA Report via")
    context.startActivity(shareIntent)
  }

  fun generateAndSharePdfReport(context: Context, record: CalculationRecord) {
    try {
      val pdfDocument = PdfDocument()
      val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 page in points
      val page = pdfDocument.startPage(pageInfo)
      val canvas: Canvas = page.canvas

      val paintNameHeader = Paint().apply {
        color = Color.rgb(229, 193, 88) // Gold
        textSize = 22f
        typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        isAntiAlias = true
      }

      val paintTitle = Paint().apply {
        color = Color.WHITE
        textSize = 15f
        typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        isAntiAlias = true
      }

      val paintSub = Paint().apply {
        color = Color.rgb(229, 193, 88)
        textSize = 13f
        typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        isAntiAlias = true
      }

      val paintBody = Paint().apply {
        color = Color.rgb(240, 240, 245)
        textSize = 11f
        isAntiAlias = true
      }

      val paintLabel = Paint().apply {
        color = Color.rgb(200, 196, 181)
        textSize = 11f
        typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        isAntiAlias = true
      }

      // Background black
      canvas.drawColor(Color.rgb(14, 14, 18))

      var y = 45f
      canvas.drawText("FAIZAN RAZA", 40f, y, paintNameHeader)
      y += 22f
      canvas.drawText("CA CALCULATOR & AUDIT SYSTEM — OFFICIAL REPORT", 40f, y, paintTitle)
      y += 22f
      canvas.drawText("Module: ${record.moduleTitle}  |  Tool: ${record.calculatorTitle}", 40f, y, paintSub)
      y += 20f
      val dateStr = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault()).format(Date(record.timestampMillis))
      canvas.drawText("Generated on: $dateStr", 40f, y, paintBody)
      y += 25f

      // Draw Gold separator line
      val paintLine = Paint().apply {
        color = Color.rgb(184, 150, 53)
        strokeWidth = 2f
      }
      canvas.drawLine(40f, y, 555f, y, paintLine)
      y += 30f

      canvas.drawText("INPUT SUMMARY", 40f, y, paintSub)
      y += 20f
      record.inputSummary.split("\n").forEach { line ->
        if (y > 780f) return@forEach
        canvas.drawText("• $line", 50f, y, paintBody)
        y += 18f
      }

      y += 15f
      canvas.drawText("RESULT ANALYSIS & SCHEDULE", 40f, y, paintSub)
      y += 20f

      for (row in record.detailedRows) {
        if (y > 780f) break
        canvas.drawText(row.label, 50f, y, paintLabel)
        canvas.drawText(row.value, 350f, y, if (row.isHighlighted) paintTitle else paintBody)
        y += 18f
        if (row.footnote.isNotEmpty()) {
          canvas.drawText("Note: ${row.footnote}", 60f, y, paintBody)
          y += 16f
        }
      }

      y += 30f
      canvas.drawLine(40f, y, 555f, y, paintLine)
      y += 20f
      canvas.drawText("CA Calculator — All-in-One Utility for Commerce Students & CA Aspirants (ICAI)", 40f, y, paintBody)

      pdfDocument.finishPage(page)

      val exportDir = File(context.cacheDir, "ca_reports")
      if (!exportDir.exists()) exportDir.mkdirs()
      val file = File(exportDir, "ca_report_${System.currentTimeMillis()}.pdf")
      val outputStream = FileOutputStream(file)
      pdfDocument.writeTo(outputStream)
      pdfDocument.close()
      outputStream.close()

      val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
      val shareIntent = Intent(Intent.ACTION_SEND).apply {
        type = "application/pdf"
        putExtra(Intent.EXTRA_STREAM, uri)
        putExtra(Intent.EXTRA_TITLE, "CA Report: ${record.calculatorTitle}")
        addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
      }
      context.startActivity(Intent.createChooser(shareIntent, "Share CA PDF Report"))
      Toast.makeText(context, "PDF Report generated & ready to share!", Toast.LENGTH_SHORT).show()
    } catch (e: Exception) {
      // Fallback to text share if PDF fails
      shareTextReport(context, record)
    }
  }
}
